// DA:WEB 2023 spring
export const githubUsers = [
	'ICerv',
	'Mariana Sarovic',
	'Iva Havranová',
	'Petra',
	'Tynuska',
	'ciiryah',
	'EndziTheNoob',
	'evadob',
	'KamilaSemotanova',
	'Doleva161',
	'Tereza-Z',
	'MarketaMiza',
	'Tetiana-byt',
	'LiudmylaLiaposhchenko',
	'SchallDa',
	'AndyW30',
	'EliskaBuocikova',
	'lindabalounova1',
	'michaelamitr',
	'NataliiaHl',
	'Filip Chalupa',
	'EliKorenc',
	'KariSalti',
	'AlexLatna',
	'Terezm',
	'EvaKovarikova',
	'alinakhop',
	'metisova',
	'Veronika Bendova',
	'Daniela73Schneider',
	'pokornajohana',
	'prosteVira',
	'Kristyna-Novakova',
	'katrinaslezakova',
	'LydieCihakova88',
	'Ariel0000ff',
	'Tetiana_M',
] as const
