// DA:WEB 2023 spring
export const githubUsers = [
	'Tynuska',
	'alinakhop',
	'AlexLatna',
	'lindabalounova1',
	'EndziTheNoob',
	'beveroni',
	'EliskaBuocikova',
	'ICerv',
	'LydieCihakova88',
	'prosteVira',
	'evadob',
	'FilipChalupa',
	'Doleva161',
	'havraiv',
	'NataliiaHl',
	'metisova',
	'EliKorenc',
	'ciiryah',
	'LiudmylaLiaposhchenko',
	'Terezm',
	'Tetiana-M-ai',
	'MarketaMiza',
	'Kristyna-Novakova',
	'PetraPek',
	'pokornajohana',
	'Ariel0000ff',
	'KamilaSemotanova',
	'SchallDa',
	'Daniela73Schneider',
	'katrinaslezakova',
	'Maree13',
	'michaelamitr',
	'LucieTrojanova',
	'AndyW30',
	'Tereza-Z',
] as const
